# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# transparency to every window
# windowrule = match:class ^(.*)$, opacity 0.94 override 0.95

# terminals
windowrule = match:class ^(kitty|foot|Alacritty)$, opacity 0.91 override 0.93

# less transparent apps
windowrule = match:class ^(org.kde.dolphin|org.kde.plasma.emojier)$, opacity 0.94 override 0.95

# Disable blur for all xwayland apps
# windowrulev2 = noblur, xwayland:1
